Refactors
inspirehep/json-merger pull request #23
Opened 2016-09-15 11:49 UTC by mihaibivol

2016-09-15 19:47 UTC, kaplun commented on README.rst
> +Module for merging JSON Objects.
We should amend also in setup.py where we say that it's an Invenio module.

2016-09-15 19:48 UTC, kaplun commented on json_merger/__init__.py
> +To use this module, first import the main class:
... you need to first import the main class:

2016-09-15 19:49 UTC, kaplun commented on json_merger/__init__.py
> +Let's assume we have JSON records in which don't have any list fields --
in which -> that

2016-09-15 19:51 UTC, kaplun commented on json_merger/__init__.py
> +If this type of conflict occurs, the merger will also populate a conflicts
conflicts -> `conflicts`

so that it's clear that it's a literal.

2016-09-15 19:52 UTC, kaplun commented on json_merger/comparator.py
> +        json_merger logic.
Uh!? What do you mean?

2016-09-15 19:54 UTC, kaplun commented on json_merger/comparator.py
"Renders"? Maybe "Consider"?

2016-09-15 20:00 UTC, kaplun requested changes
What happened to configuration you had prepared so far? It could very well sit into an examples or contrib directory...

2016-09-19 11:12 UTC, mihaibivol commented on json_merger/comparator.py
> +        json_merger logic.
To leave the signatures correct, otherwise it will blow. A pretty useless comment actually :)

2016-09-19 11:15 UTC, kaplun commented on json_merger/comparator.py
> +        json_merger logic.
well then one can override the constructor as long as the signature is the same :P

2016-09-19 11:18 UTC, mihaibivol commented on json_merger/comparator.py
> +        json_merger logic.
:bike: :bike: :bike: Older logic was using self.l1 and self.l2. But whatever this is Python, devs should know what they do when they inherit from things. The example that I have shows you how to override two things.

2016-09-19 11:22 UTC, kaplun commented on json_merger/comparator.py
> +        json_merger logic.
Let me do my stupid comment any way. :-P I can't really understand the whole rest of the refactoring unless I can focus on it for 24 hours in a row :-P

2016-09-19 11:26 UTC, kaplun commented on json_merger/comparator.py
> +        json_merger logic.
I mean... docstrings at this point are the only thing I can review. For the rest I assumes tests and APIs are the final source of truth.

Gaaah :boom:

2016-09-19 11:39 UTC, mihaibivol commented
Logicwise, i did three things

* Moved some classes in dedicated files
* Redid the matching logic in graph_builder.
* Cache all matching pairs in comparators so any get matches call will be
done in constant lookup.

Other than that I did doc tests. I should soon push the last bullets and
refactor a bit the API ones. Should be ready today :)

On Mon, Sep 19, 2016, 13:26 Samuele Kaplun <notifications@github.com> wrote:

> *@kaplun* commented on this pull request.
> ------------------------------
>
> In json_merger/comparator.py
> <https://github.com/inspirehep/json-merger/pull/23>:
>
> >
>      def __init__(self, l1, l2):
> +        """
> +        Do not override the constructor since it will be called by the
> +        json_merger logic.
>
> I mean... docstrings at this point are the only thing I can review. For
> the rest I assumes tests and APIs are the final source of truth.
>
> Gaaah 💥
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/inspirehep/json-merger/pull/23>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAd6jdMyiFO5k7zyLTH6n01O4OnUp2Ieks5qrnFmgaJpZM4J9xvb>
> .
>

2016-09-19 21:47 UTC, mihaibivol commented on README.rst
> +Module for merging JSON Objects.
Done :)

2016-09-19 22:08 UTC, kaplun commented
Good if you apply my small points, and squash the commits LGTM

2016-09-20 07:44 UTC, kaplun approved these changes

2016-09-20 07:45 UTC, merged