merger: parametrize strategy for fallback field
inspirehep/json-merger pull request #30
Opened 2017-05-02 11:29 UTC by rikirenz

* Adds the possibility to pass a dictionary in order
to parametrize the fallback strategy for fields that
are not lists.

Signed-off-by: Riccardo Candido <riccardo.candido@gmail.com>

2017-05-02 11:31 UTC, rikirenz commented
We are missing acceptance tests for the introduced feature. They are going to be added in a second commit. :dancing_men:

2017-05-02 13:14 UTC, ammirate requested changes
Code looks fine, just few things to review and also more tests should be added

2017-05-02 13:14 UTC, ammirate commented on json_merger/dict_merger.py
> +            head = patches[i].first_patch
Maybe using a more pythonic style here would improve readability:
```
for patch in patches:
    head = patch.first_patch
```

2017-05-02 13:14 UTC, ammirate commented on json_merger/dict_merger.py
> +        if type(path) is list:
Better use built-in function `isinstance`.
For more info: https://docs.python.org/2/library/functions.html#isinstance

2017-05-02 13:14 UTC, ammirate commented on json_merger/dict_merger.py
> +
Not sure here what's the role of `i`, maybe you can remove it.

2017-05-02 13:14 UTC, ammirate commented on tests/unit/test_dict_merger.py
> +
Let's keep the code clean removing the commented code ;)

2017-05-02 13:14 UTC, ammirate commented on tests/unit/test_dict_merger.py
> +
We should assert also that the raised error `excinfo` contains exactly what we expect.

2017-05-02 13:14 UTC, ammirate commented on tests/unit/test_dict_merger.py
> +
Same as above.

2017-05-02 13:14 UTC, ammirate commented on tests/unit/test_dict_merger.py
> +def test_get_custom_strategies():
Since this test is working on deep logic, some comments would really be helpful to maintain it (as well as the following tests).

2017-05-02 13:14 UTC, ammirate commented on tests/unit/test_dict_merger.py
> +    expected_strategies = ['s', 's', 's', 's']
IMO, would be also interesting a mixed `expected_strategies` as a test

2017-05-02 14:36 UTC, rikirenz commented on json_merger/dict_merger.py
> +
In this case is necessary because we modify the `list_path` object in the for cycle :smile:

2017-05-02 14:37 UTC, rikirenz commented on tests/unit/test_dict_merger.py
> +    expected_strategies = ['s', 's', 's', 's']
Let's do it!!!!

2017-05-03 09:18 UTC, jacquerie commented on json_merger/dict_merger.py
> +            for i in range(len(e.content)):
Use `enumerate`.

2017-05-03 09:29 UTC, kaplun commented on json_merger/dict_merger.py
> +                 data_lists=None, custom_ops={}):
Is this `_op` Vs. `_ops` intended?

2017-05-03 09:30 UTC, kaplun commented on json_merger/dict_merger.py
> +                 data_lists=None, custom_ops={}):
Also would be nice to add the missing docstring to explain the structure of `custom_ops`.

2017-05-03 09:32 UTC, kaplun commented on json_merger/dict_merger.py
> +
I think this should then be factored out into a separate helper, because it's not obvious what it does.

2017-05-03 09:39 UTC, kaplun commented on json_merger/dict_merger.py
> +
Can't it get away without the loop? e.g. `while list_path:`

2017-05-04 09:12 UTC, rikirenz commented on json_merger/dict_merger.py
> +                 data_lists=None, custom_ops={}):
Yes is intended! We are going to add the `doc_string`

2017-05-12 07:06 UTC, merged